# Generated by Django 4.2.30 on 2026-09-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Official university student ID, e.g., 2023-1-60-123.', max_length=20, unique=True)),
                ('program', models.CharField(choices=[('BSC_CSE', 'B.Sc. in CSE'), ('BSC_EEE', 'B.Sc. in EEE'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('BSC_CE', 'B.Sc. in Civil Engineering'), ('MSC_CSE', 'M.Sc. in CSE')], default='BSC_CSE', max_length=20)),
                ('batch', models.CharField(blank=True, help_text='e.g., 2023-24', max_length=20)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('current_semester', models.ForeignKey(blank=True, help_text='Currently-enrolled semester.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.semester')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['-id'],
            },
        ),
    ]
