# Generated by Django 4.2.30 on 2026-09-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('lecturer', 'Lecturer'), ('sr_lecturer', 'Senior Lecturer'), ('asst_prof', 'Assistant Professor'), ('assoc_prof', 'Associate Professor'), ('professor', 'Professor')], default='lecturer', max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('office_room', models.CharField(blank=True, max_length=50)),
                ('cv_link', models.URLField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['-id'],
            },
        ),
    ]
