# Generated by Django 4.2.30 on 2026-09-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('student', 'Students'), ('teacher', 'Teachers'), ('admin', 'Admins'), ('department', 'Department'), ('course', 'Course')], default='all', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Required only when audience=course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='academics.course')),
                ('department', models.ForeignKey(blank=True, help_text='Required only when audience=department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='academics.department')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
